blank_issues_enabled: false
contact_links:
  - name: ğŸ”’ï¸ Security Issue
    url: https://typo3.org/community/teams/security
    about: If you encounter a security issue ğŸ‘¿, please reach out **only** to the TYPO3 Security Team by writing to security (at) typo3.org. Please don't share the information with the Documentation Team or anyone else.
  - name: â“ Ask question
    url: https://typo3.slack.com/app_redirect?channel=C028JEPJL
    about: Please ask questions in the Slack channel "#typo3-documentation" ğŸ¤—
