# Settings.yml
---
conf.py:
  project: TYPO3 CMS Coding Guidelines
  copyright: 2000-2015
  version: 7
  release: 7
  intersphinx_mapping:
    t3api:
    - https://docs.typo3.org/typo3cms/CoreApiReference/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-CodingGuidelines
    github_branch: latest
  latex_documents:
  - - Index
    - t3cgl.tex
    - Coding Guidelines
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}

...
