# Settings.yml
---
conf.py:
  project: TypoScript Syntax and In-depth Study
  copyright: 2000-2014
  version: 7
  release: 7
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference
    - null
    t3templating:
    - http://docs.typo3.org/typo3cms/TemplatingTutorial/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax
    github_branch: latest
  latex_documents:
  - - Index
    - t3tssyntax.tex
    - TypoScript Syntax and In-depth Study
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
