# Settings.yml
---
conf.py:
  project: TYPO3 Core APIs
  copyright: 2000-2014
  version: 7
  release: 7
  intersphinx_mapping:
    t3cgl:
    - http://docs.typo3.org/typo3cms/CodingGuidelinesReference/
    - null
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
    t3extbasebook:
    - http://docs.typo3.org/typo3cms/ExtbaseFluidBook/
    - null
    t3fal:
    - http://docs.typo3.org/typo3cms/FileAbstractionLayerReference/
    - null
    t3inside:
    - http://docs.typo3.org/typo3cms/InsideTypo3Reference/
    - null
    t3tca:
    - http://docs.typo3.org/typo3cms/TCAReference/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference/
    - null
    t3skinning:
    - http://docs.typo3.org/typo3cms/SkinningReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3services:
    - http://docs.typo3.org/typo3cms/Typo3ServicesReference/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi
    github_branch: latest
  latex_documents:
  - - Index
    - t3api.tex
    - Core APIs
    - Documentation Team
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
