name: tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '42 5 * * *'

jobs:
  testsuite:
    name: all tests
    runs-on: ubuntu-20.04
    strategy:
      # This prevents cancellation of matrix job runs, if one or more already failed
      # and let the remaining matrix jobs be be executed anyway.
      fail-fast: false
      matrix:
        # @todo: Change back to to php: [ '8.1', '8.2' ] if JWT token library from core is working PHP8.2
        php: [ '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add HTTP Basic Auth Credentials for composer
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: CGL
        if: ${{ matrix.php <= '8.1' }}
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.php }} -s cgl -n

