name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC

jobs:
  lint:
    # Run always on push/PR, but only run on schedule in the main repo
    if: github.event_name != 'schedule' || github.repository == 'TYPO3-Documentation/TYPO3CMS-Reference-CoreApi'
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

  quality:
    # Run always on push/PR, but only run on schedule in the main repo
    if: github.event_name != 'schedule' || github.repository == 'TYPO3-Documentation/TYPO3CMS-Reference-CoreApi'
    name: Quality
    runs-on: ubuntu-latest
    env:
      php: '8.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerValidate

      - name: Composer normalize
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerNormalize -n

      - name: CGL
        run: Build/Scripts/runTests.sh -n -p ${{ env.php }} -s cgl -n

      - name: Check Rst
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s checkRst

      - name: Lint YAML
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s yamlLint
