name: tests

on:
  push:
  pull_request:

jobs:
  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    env:
      php: '8.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerValidate

      - name: Composer normalize
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerNormalize -n

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s lint

      - name: CGL
        run: Build/Scripts/runTests.sh -n -p ${{ env.php }} -s cgl -n

      - name: Check Rst
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s checkRst

      - name: Lint YAML
        run: .Build/bin/yaml-lint Documentation/
